name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, Tag, and Push Docker Image
      env:
        ECR_REGISTRY: <aws_account_id>.dkr.ecr.us-east-1.amazonaws.com
        IMAGE_NAME: my-app
      run: |
        docker build -t $IMAGE_NAME .
        docker tag $IMAGE_NAME:latest $ECR_REGISTRY/$IMAGE_NAME:latest
        docker push $ECR_REGISTRY/$IMAGE_NAME:latest

